### PR TITLE
Migrate to Null-Safety

### LINKED ISSUE #26: Null Safety Support
Any plan of adding null safety support in this package?

### PR DESCRIPTION
**Pull request by felixgabler**
closes #26

### CODE REVIEW

**Comment by erickok** [comment]
@felixgabler  Thanks for making this PR. I am starting to use it but did notice that it still reports errors:

```
../../../.pub-cache/git/preload_page_view-bcfcfcc7eff893648eabddcb733e16388a2301eb/lib/preload_page_view.dart:347:33: Warning: Operand of null-aware operation '!' has type 'double' which excludes null.
    return _getPixels(position, page!.roundToDouble());
```
Is this something yet to be solved?

**Comment by felixgabler** [comment]
> @felixgabler Thanks for making this PR. I am starting to use it but did notice that it still reports errors:
> Is this something yet to be solved?

Thanks for your notice! I actually forgot to push my latest version. It should be fixed now

**Comment by erickok** [comment]
@felixgabler Yes, that did it, nice. Thanks!

**Review by octomato — APPROVED** [review]

**Comment by thherman** [comment]
When is this getting released on pub.dev ?

**Pull request merged**
